### ISSUE TITLE
Readme and Docker Improvements

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#147]
- use a template for consistency
- add instructions to use sonar scanner
- add instructions to deploy
- docker-compose.yml

** ACCEPTANCE CRITERIA **
- common layout for readmes
- instructions to deploy
- instructions for sonarcloud
- readme instructions and docker-compose files coordination

**Comment by wltrf** [comment]
take into consideration changes from #141

**Comment by DPigeon** [comment]
Hey @wltrf can you inject the dev/prod profile when deploying in this story please? Or inject the env dependencies in the jar file. You probably already did this small task at this point but yeah we need this since the backend is not being deployed properly. Those are the docker logs from the backend container:

![hi](https://user-images.githubusercontent.com/37888675/99910424-ec4e6800-2cbb-11eb-8b32-5ebb41877fe6.png)

**Comment by DPigeon** [comment]
What we could do is pass the docker env args into the action we use to build and publish the image. Example:
```
- name: Build & Publish Backend
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
           ALPACA_KEY: ${{ secrets.ALPACA_KEY_ID }}
           IEXCLOUD_KEY: ${{ secrets.IEXCLOUD_KEY }}
        with:
          name: dpigeon/money-tree/backend
          registry: docker.pkg.github.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: backend
          dockerfile: Dockerfile
          tags: ${{ env.VERSION_NAME }}
```

However, I read that the secrets can be retrieved easily with ```docker inspect``` or ```docker history```.  A multi-stage builds would solve this issue. See https://vsupalov.com/docker-build-pass-environment-variables/
@wltrf 
@razine-bensari
